# ElastiFlow
export ELASTIFLOW_GEOIP_DB_PATH=/etc/logstash/elastiflow/geoipdbs
export ELASTIFLOW_DICT_PATH=/etc/logstash/elastiflow/dictionaries
export ELASTIFLOW_TEMPLATE_PATH=/etc/logstash/elastiflow/templates

export ELASTIFLOW_RESOLVE_IP2HOST=true
export ELASTIFLOW_NAMESERVER=127.0.0.1

export ELASTIFLOW_ES_HOST=127.0.0.1
export ELASTIFLOW_ES_USER=elastic
export ELASTIFLOW_ES_PASSWD=changeme

export ELASTIFLOW_NETFLOW_HOST=0.0.0.0
export ELASTIFLOW_NETFLOW_PORT=2055
export ELASTIFLOW_NETFLOW_LASTSW_TIMESTAMP=true
export ELASTIFLOW_NETFLOW_TZ=UTC

export ELASTIFLOW_SFLOW_HOST=0.0.0.0
export ELASTIFLOW_SFLOW_PORT=6343

export ELASTIFLOW_IPFIX_TCP_HOST=0.0.0.0
export ELASTIFLOW_IPFIX_TCP_PORT=4739
export ELASTIFLOW_IPFIX_UDP_HOST=0.0.0.0
export ELASTIFLOW_IPFIX_UDP_PORT=4739
